In [ ]:
# Sentiment Analysis project over a twitter review dataset
# ML approach and DL approaches are implemented
# Author: Muhammad Humayun Khan

import pandas as pd
import numpy as np

dataset_path = "../datasets/sentiment_analysis/train.csv"

df = pd.read_csv(dataset_path,encoding = 'latin-1')

df.head()

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,morning,0-20,Afghanistan,38928346,652860.0,60
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative,noon,21-30,Albania,2877797,27400.0,105
2,088c60f138,my boss is bullying me...,bullying me,negative,night,31-45,Algeria,43851044,2381740.0,18
3,9642c003ef,what interview! leave me alone,leave me alone,negative,morning,46-60,Andorra,77265,470.0,164
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative,noon,60-70,Angola,32866272,1246700.0,26

In [3]:
# the dataset having extra features and we will keep the important one
df = df[['text','sentiment']]
df.sample(10)

                                                    text sentiment
775                           The World is just amazing!  positive
13272  I feel useless I don`t know what to do right n...  negative
13318                               no southland this wk   neutral
7763                 Yeah, it`s good.  Just startled me.  positive
24334  A central lesson of history is that States are...  negative
19265   thanks dude. Being a low level business man i...   neutral
11244  Beautiful monday morning  so happy  http://myl...  positive
13415  _bbA Ooh, nice  Well I guess not nice at the m...  positive
25262  _ai_08  Yeah hopefully but if not then maybe  ...  positive
20960   haha! you`re so funny, Mikee .. you`re probab...   neutral

In [4]:
df.shape

(27481, 2)

In [5]:
# checking the essentials in the dataset
df.isnull().sum()

text         1
sentiment    0
dtype: int64

In [6]:
# finding percentages of the class for the imbalanced dataset
class_count = df['sentiment'].value_counts()

# calculate the percentage as well
class_percentage = round((class_count / len(df)) * 100, 2).astype(str) + '%'

# combine both into dataframe
class_summary = pd.DataFrame({
    'Class':class_count.index,
    'Count':class_count.values,
    'Cent':class_percentage.values
})

class_summary

      Class  Count    Cent
0   neutral  11118  40.46%
1  positive   8582  31.23%
2  negative   7781  28.31%

In [7]:
# text preprocessing 
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Initialize stopwords and lemmatizer
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Lowercase
    text = text.lower()

    # Remove URLs, mentions, hashtags
    text = re.sub(r"http\S+|www\S+|@\S+|#\S+", "", text)

    # Remove punctuation and numbers
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords and lemmatize
    cleaned_tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return ' '.join(cleaned_tokens)

# Drop rows with missing text
df = df.dropna(subset=['text'])

# Apply to DataFrame
df['clean_text'] = df['text'].apply(preprocess_text)

# View cleaned output
df[['text', 'clean_text']].sample(10)

,text,clean_text
20944,i wish it was summer,wish summer
11692,that`s so weird seeing your MySpace page with...,thats weird seeing myspace page without delete...
5727,"I`d respond, if I were going",id respond going
21309,feeling the need for more advil.,feeling need advil
21924,mmmm... looks so yummy! good seeing u,mmmm look yummy good seeing u
24367,"thanks for adding, no befriending, no, uh oh ...",thanks adding befriending uh oh never mind thanks
24804,i dont like funerals,dont like funeral
21191,"is Chillin`, listening to Tunes",chillin listening tune
2393,_J think so.. although think i am being ignore...,j think although think ignored good day
21004,Hey its back!! (robluketic live > http://u...,hey back robluketic live

In [8]:
# Text Vectorization process in the NLP pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer(max_features=5000)

# Fit and transform the cleaned text
X = vectorizer.fit_transform(df['clean_text'])

# Target variable (labels)
y = df['sentiment']

# Shape of transformed data
print("TF-IDF Shape:", X.shape)

TF-IDF Shape: (27480, 5000)

In [9]:
# As the data is converted into the numerical now we need the train/test split
from sklearn.model_selection import train_test_split

# Stratified train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y      # for balanced dataset
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (21984, 5000)
Test shape: (5496, 5000)

In [10]:
# train the model with the LogisticRegression
from sklearn.linear_model import LogisticRegression

# Initialize and train the model
model = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

In [11]:
# evaluate the result
from sklearn.metrics import classification_report, confusion_matrix

# Evaluation metrics
print("Classification Report:\n")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Classification Report:

              precision    recall  f1-score   support

    negative       0.66      0.69      0.67      1556
     neutral       0.65      0.66      0.65      2223
    positive       0.76      0.72      0.74      1717

    accuracy                           0.69      5496
   macro avg       0.69      0.69      0.69      5496
weighted avg       0.69      0.69      0.69      5496

Confusion Matrix:

[[1067  405   84]
 [ 447 1458  318]
 [ 100  375 1242]]

In [12]:
# lets predict the new text
def predict_sentiment(text):
    # Preprocess
    clean = preprocess_text(text)
    
    # TF-IDF transform
    vector = vectorizer.transform([clean])
    
    # Predict
    pred = model.predict(vector)[0]
    return pred

print(predict_sentiment("I absolutely love this product!"))
print(predict_sentiment("This is the worst thing ever."))
print(predict_sentiment("It’s okay, I guess. Nothing special."))

# the output is good in terms of the normal sentences

positive
negative
neutral

In [13]:
# let's try the sarcasm sentences
print(predict_sentiment("Oh great, another Monday. Just what I needed")) # the output should be negative as sarcasm sentence
print(predict_sentiment("I don’t think this is a bad movie")) # the output should be positive as negative handling sentence
print(predict_sentiment("It was fun, but the ending ruined everything")) # the output should be neutral/negative as mixed/ambigous sentence
print(predict_sentiment("Yeah, sure whatever!")) # the output should be negative as passive aggressive tone

positive
negative
negative
neutral

In [14]:
# Now I will apply the Deep Leanring approach as the ML approach didn't work on the sarcasm sentences.
# The steps are:
# 1. Load the already prepared data
# 2. Tokenization and padding by using the Keras and pad_sequences
# 3. I will use the pretrained GloVe model as due to heavy load of Word2Vec
# 4. I will create the Embedding matrix by mapping the tokenizer word index to the GloVe vectors
# 5. Build the LSTM model with Embedding layer, LSTM layer, and Dense layer with softmax activation
# 6. Train the model with validation split and evaluate using accuracy and F1-score

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Encode the labels
label_encoder = LabelEncoder()
df['sentiment_encoded'] = label_encoder.fit_transform(df['sentiment'])

# Save label mapping
label_map = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

In [18]:

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'], df['sentiment_encoded'], test_size=0.2, stratify=df['sentiment_encoded'], random_state=42
)

In [19]:
import pandas as pd
import numpy as np
import re
import nltk
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.utils import to_categorical

from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, accuracy_score, f1_score

# 2. Tokenization and Padding
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

max_len = 100
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len, padding='post', truncating='post')

# Convert labels to categorical (one-hot)
num_classes = len(np.unique(y_train))
y_train_cat = to_categorical(y_train, num_classes=num_classes)
y_test_cat = to_categorical(y_test, num_classes=num_classes)

In [21]:
# 3. Load GloVe embeddings
embedding_index = {}
embedding_dim = 100
glove_path = 'embeddings/glove.6B.100d.txt'  # Path to downloaded GloVe file

with open(glove_path, encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vec = np.asarray(values[1:], dtype='float32')
        embedding_index[word] = vec

print("GloVe embeddings loaded:", len(embedding_index))

GloVe embeddings loaded: 400000

In [22]:
# 4. Create embedding matrix
word_index = tokenizer.word_index
num_words = min(vocab_size, len(word_index) + 1)

embedding_matrix = np.zeros((num_words, embedding_dim))
for word, i in word_index.items():
    if i < vocab_size:
        embedding_vector = embedding_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [28]:
# 5. Build LSTM model
model = Sequential()
model.add(Embedding(input_dim=num_words, output_dim=embedding_dim, weights=[embedding_matrix], input_length=max_len, trainable=False))
model.add(Bidirectional(LSTM(128, return_sequences=False)))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.build(input_shape=(None, max_len))
model.summary()

d:\Drive I\Work\Summer 2025 Personal Growth\natural_language_processing\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 100, 100)       │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 256)            │       234,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,251,139 (4.77 MB)

 Trainable params: 251,139 (981.01 KB)

 Non-trainable params: 1,000,000 (3.81 MB)

In [29]:
# 6. Train the model
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights = dict(enumerate(class_weights))

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

history = model.fit(
    X_train_pad, y_train_cat,
    validation_data=(X_test_pad, y_test_cat),
    epochs=15,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[early_stop]
)

Epoch 1/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 106s 148ms/step - accuracy: 0.5578 - loss: 0.9190 - val_accuracy: 0.6732 - val_loss: 0.7631
Epoch 2/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 98s 142ms/step - accuracy: 0.6682 - loss: 0.7614 - val_accuracy: 0.6810 - val_loss: 0.7368
Epoch 3/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 100s 146ms/step - accuracy: 0.6930 - loss: 0.7082 - val_accuracy: 0.6914 - val_loss: 0.7187
Epoch 4/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 106s 154ms/step - accuracy: 0.7071 - loss: 0.6865 - val_accuracy: 0.6969 - val_loss: 0.7212
Epoch 5/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 109s 159ms/step - accuracy: 0.7207 - loss: 0.6637 - val_accuracy: 0.6918 - val_loss: 0.7238
Epoch 6/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 100s 146ms/step - accuracy: 0.7327 - loss: 0.6396 - val_accuracy: 0.7045 - val_loss: 0.6971
Epoch 7/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 93s 135ms/step - accuracy: 0.7464 - loss: 0.6100 - val_accuracy: 0.7034 - val_loss: 0.6970
Epoch 8/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 92s 134ms/step - accuracy: 0.7551 - loss: 0.5891 - val_accuracy: 0.7031 - val_loss: 0.7065
Epoch 9/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 151s 147ms/step - accuracy: 0.7593 - loss: 0.5743 - val_accuracy: 0.7038 - val_loss: 0.7102
Epoch 10/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 96s 140ms/step - accuracy: 0.7740 - loss: 0.5511 - val_accuracy: 0.7027 - val_loss: 0.7368

In [30]:
# Evaluation
y_pred = model.predict(X_test_pad)
y_pred_labels = np.argmax(y_pred, axis=1)
print("\nClassification Report:")
print(classification_report(y_test, y_pred_labels, target_names=label_encoder.classes_))
print("Accuracy:", accuracy_score(y_test, y_pred_labels))
print("F1 Score:", f1_score(y_test, y_pred_labels, average='weighted'))

172/172 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step

Classification Report:
              precision    recall  f1-score   support

    negative       0.71      0.66      0.68      1556
     neutral       0.68      0.67      0.68      2223
    positive       0.73      0.78      0.75      1717

    accuracy                           0.70      5496
   macro avg       0.71      0.70      0.70      5496
weighted avg       0.70      0.70      0.70      5496

Accuracy: 0.7034206695778749
F1 Score: 0.7026665315678561

In [31]:
# Prediction Function
def predict_sentiment(text):
    cleaned = preprocess_text(text)
    seq = tokenizer.texts_to_sequences([cleaned])
    pad = pad_sequences(seq, maxlen=max_len, padding='post')
    pred = model.predict(pad)[0]
    label_idx = np.argmax(pred)
    confidence = round(pred[label_idx] * 100, 2)
    sentiment = label_encoder.inverse_transform([label_idx])[0]
    return sentiment, confidence

# Example Predictions
print(predict_sentiment("I absolutely love this!"))
print(predict_sentiment("Worst thing I've ever used."))
print(predict_sentiment("Just an average experience."))
print(predict_sentiment("Oh great, another Monday. Just what I needed")) # the output should be negative as sarcasm sentence
print(predict_sentiment("I don’t think this is a bad movie")) # the output should be positive as negative handling sentence
print(predict_sentiment("It was fun, but the ending ruined everything")) # the output should be neutral/negative as mixed/ambigous sentence
print(predict_sentiment("Yeah, sure whatever!")) # the output should be negative as passive aggressive tone

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
('positive', 90.72)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
('negative', 91.53)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
('neutral', 41.04)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
('positive', 84.47)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
('negative', 69.87)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
('neutral', 48.74)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
('neutral', 46.41)

In [32]:
import re
import string
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)  # Remove URLs
    text = re.sub(r"[^A-Za-z0-9()!?\'`]", " ", text)  # Remove punctuation
    text = re.sub(r"\s+", " ", text).strip()

    # Expand common negations
    text = re.sub(r"don't", "do not", text)
    text = re.sub(r"doesn't", "does not", text)
    text = re.sub(r"won't", "will not", text)
    text = re.sub(r"can't", "cannot", text)
    text = re.sub(r"n't", " not", text)
    
    # Remove stop words (optional)
    text = " ".join([word for word in text.split() if word not in stop_words])

    return text

[nltk_data] Downloading package stopwords to d:\Drive I\Work\Summer
[nltk_data]     2025 Personal
[nltk_data]     Growth\natural_language_processing\venv\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [33]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 10000
max_len = 100

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len, padding='post', truncating='post')

In [34]:
from tensorflow.keras.utils import to_categorical
import numpy as np

num_classes = len(np.unique(y_train))
y_train_cat = to_categorical(y_train, num_classes=num_classes)
y_test_cat = to_categorical(y_test, num_classes=num_classes)

In [35]:
embedding_index = {}
embedding_dim = 100
with open("embeddings/glove.6B.100d.txt", encoding="utf8") as f:
    for line in f:
        values = line.split()
        word = values[0]
        vec = np.asarray(values[1:], dtype="float32")
        embedding_index[word] = vec

word_index = tokenizer.word_index
num_words = min(vocab_size, len(word_index) + 1)

embedding_matrix = np.zeros((num_words, embedding_dim))
for word, i in word_index.items():
    if i < vocab_size:
        embedding_vector = embedding_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [ ]:
# custom attention layer
from tensorflow.keras.layers import Layer
import tensorflow.keras.backend as K

class AttentionLayer(Layer):
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(name="att_weight", shape=(input_shape[-1], 1),
                                 initializer="normal", trainable=True)
        self.b = self.add_weight(name="att_bias", shape=(input_shape[1], 1),
                                 initializer="zeros", trainable=True)
        super(AttentionLayer, self).build(input_shape)

    def call(self, inputs):
        e = K.tanh(K.dot(inputs, self.W) + self.b)
        e = K.squeeze(e, axis=-1)
        alpha = K.softmax(e)
        alpha = K.expand_dims(alpha, axis=-1)
        context = inputs * alpha
        context = K.sum(context, axis=1)
        return context

In [ ]:
# build model
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, Bidirectional, LSTM, Dense, Dropout

input_layer = Input(shape=(max_len,))
embedding_layer = Embedding(input_dim=num_words, output_dim=embedding_dim,
                            weights=[embedding_matrix], input_length=max_len, trainable=False)(input_layer)

bilstm = Bidirectional(LSTM(128, return_sequences=True))(embedding_layer)
dropout1 = Dropout(0.4)(bilstm)

attention_output = AttentionLayer()(dropout1)
dropout2 = Dropout(0.3)(attention_output)
dense = Dense(64, activation='relu')(dropout2)
output = Dense(num_classes, activation='softmax')(dense)

model = Model(inputs=input_layer, outputs=output)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

d:\Drive I\Work\Summer 2025 Personal Growth\natural_language_processing\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

WARNING:tensorflow:From d:\Drive I\Work\Summer 2025 Personal Growth\natural_language_processing\venv\lib\site-packages\keras\src\backend\tensorflow\core.py:232: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_5 (Embedding)         │ (None, 100, 100)       │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_7 (Bidirectional) │ (None, 100, 256)       │       234,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 100, 256)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ attention_layer                 │ (None, 256)            │           356 │
│ (AttentionLayer)                │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,251,495 (4.77 MB)

 Trainable params: 251,495 (982.40 KB)

 Non-trainable params: 1,000,000 (3.81 MB)

In [44]:
# train model
from tensorflow.keras.callbacks import EarlyStopping

class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights = dict(enumerate(class_weights))

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

history = model.fit(
    X_train_pad, y_train_cat,
    validation_data=(X_test_pad, y_test_cat),
    epochs=15,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[early_stop]
)

Epoch 1/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 153s 214ms/step - accuracy: 0.5323 - loss: 0.9421 - val_accuracy: 0.6827 - val_loss: 0.7563
Epoch 2/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 169s 166ms/step - accuracy: 0.6832 - loss: 0.7373 - val_accuracy: 0.6971 - val_loss: 0.7235
Epoch 3/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 114s 166ms/step - accuracy: 0.7136 - loss: 0.6946 - val_accuracy: 0.7025 - val_loss: 0.7087
Epoch 4/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 114s 166ms/step - accuracy: 0.7277 - loss: 0.6580 - val_accuracy: 0.7109 - val_loss: 0.6921
Epoch 5/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 114s 165ms/step - accuracy: 0.7352 - loss: 0.6433 - val_accuracy: 0.7078 - val_loss: 0.6993
Epoch 6/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 114s 167ms/step - accuracy: 0.7522 - loss: 0.6188 - val_accuracy: 0.7171 - val_loss: 0.7025
Epoch 7/15
687/687 ━━━━━━━━━━━━━━━━━━━━ 115s 168ms/step - accuracy: 0.7648 - loss: 0.5831 - val_accuracy: 0.7131 - val_loss: 0.7164

In [45]:
# evaluate model
y_pred = model.predict(X_test_pad)
y_pred_labels = np.argmax(y_pred, axis=1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_labels, target_names=label_encoder.classes_))
print("Accuracy:", accuracy_score(y_test, y_pred_labels))
print("F1 Score:", f1_score(y_test, y_pred_labels, average='weighted'))

172/172 ━━━━━━━━━━━━━━━━━━━━ 13s 71ms/step

Classification Report:
              precision    recall  f1-score   support

    negative       0.68      0.71      0.70      1556
     neutral       0.69      0.68      0.68      2223
    positive       0.77      0.75      0.76      1717

    accuracy                           0.71      5496
   macro avg       0.71      0.71      0.71      5496
weighted avg       0.71      0.71      0.71      5496

Accuracy: 0.7108806404657934
F1 Score: 0.7110005789971561

In [46]:
# prediction function with threshold
def predict_sentiment(text, threshold=60):
    cleaned = preprocess_text(text)
    seq = tokenizer.texts_to_sequences([cleaned])
    pad = pad_sequences(seq, maxlen=max_len, padding='post')
    pred = model.predict(pad)[0]
    label_idx = np.argmax(pred)
    confidence = round(pred[label_idx] * 100, 2)

    if confidence < threshold:
        return "ambiguous", confidence

    sentiment = label_encoder.inverse_transform([label_idx])[0]
    return sentiment, confidence

In [47]:
# examples predictions
(predict_sentiment("I absolutely love this!"))                       # positive
print(predict_sentiment("Worst thing I've ever used."))                   # negative
print(predict_sentiment("Just an average experience."))                   # ambiguous
print(predict_sentiment("Oh great, another Monday. Just what I needed"))  # negative (sarcasm)
print(predict_sentiment("I don’t think this is a bad movie"))             # positive
print(predict_sentiment("It was fun, but the ending ruined everything"))  # ambiguous
print(predict_sentiment("Yeah, sure whatever!"))                          # neutral/ambiguous

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
('negative', 96.37)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
('ambiguous', 45.13)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
('positive', 81.63)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
('negative', 85.54)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
('ambiguous', 46.62)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
('ambiguous', 55.47)